sudo: false
language: python
python:
  - 3.5
  - 3.6

env:
  - FLASK=0.12.2

install:

  - pip install python-coveralls
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install Flask==$FLASK

  - pip install -r requirements.txt

script: nosetests --with-coverage

after_success:
  - coveralls
